# Generated by Django 5.0.4 on 2024-04-10 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haqqında_niyəbiz',
            name='mətni',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
