# Generated by Django 5.0.4 on 2024-04-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_haqqında_niyəbiz_mətni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Haqqında_niyəbiz',
        ),
    ]
