# Generated by Django 5.0.2 on 2024-04-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=100000)),
                ('history', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='news img')),
            ],
        ),
        migrations.CreateModel(
            name='news_video_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video', models.FileField(blank=True, null=True, upload_to='video', verbose_name='news video')),
            ],
        ),
    ]
